name: NodeJS / GitHub Actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "starting build from ${{ github.repository }}"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm test
